apiVersion: v1
kind: Secret
metadata:
  name: {{ include "employee-management-chart.fullname" . }}-secret
type: Opaque
stringData:
  datasource-password: {{ .Values.spring.datasource.password | quote }}
  datasource-username: {{ .Values.spring.datasource.username | quote }}
