server.port=8000

spring.datasource.url=jdbc:mysql://host.docker.internal:3306/employeemanagement
spring.datasource.username=root
spring.datasource.password=welcome1

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


############################################
# Tomcat Thread Pool
############################################
server.tomcat.threads.max=200
server.tomcat.threads.min-spare=20
server.tomcat.accept-count=100

############################################
# HikariCP Connection Pool
############################################
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000