name: Employee Management CI

on:
  push:
    branches: [ "main", "master", "feature-employee-update" ]

permissions:
  contents: read
  packages: write
  
env:
  IMAGE_NAME: employee-management
  CHART_PATH: helm/employee-management

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}

      - name: Build
        run: mvn clean verify

      # ------------------------------------------------
      # Generate Version (Menggunakan Run Number Gitea)
      # ------------------------------------------------
      - name: Generate Image Version
        id: versioning
        shell: powershell
        run: |
          $version="1.0.${{ github.run_number }}"
          Write-Output "::set-output name=IMAGE_VERSION::$version"
          Write-Host "Version Otomatis Baru = $version"

      # ------------------------------------------------
      # Docker Build & Push
      # ------------------------------------------------
      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker
        shell: powershell
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/employee-management:${{ steps.versioning.outputs.IMAGE_VERSION }} .

      - name: Push Docker
        shell: powershell
        run: |
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/employee-management:${{ steps.versioning.outputs.IMAGE_VERSION }}

      # ------------------------------------------------
      # Update values.yaml
      # ------------------------------------------------
      - name: Update values.yaml
        shell: powershell
        run: |
          $valuesPath = "${{ env.CHART_PATH }}/values.yaml"
          $newVer = "${{ steps.versioning.outputs.IMAGE_VERSION }}"
          (Get-Content $valuesPath) -replace 'tag:.*', ("tag: `"$newVer`"") | Set-Content $valuesPath        

      - name: Verify values.yaml
        shell: powershell
        run: |
          Write-Host "===== Hasil Update values.yaml ====="
          Get-Content "${{ env.CHART_PATH }}/values.yaml"     

      # ------------------------------------------------
      # Helm Steps
      # ------------------------------------------------
      - name: Helm Lint
        run: helm lint ${{ env.CHART_PATH }} --debug

      - name: Helm Package
        run: |
          helm package ${{ env.CHART_PATH }} --version ${{ steps.versioning.outputs.IMAGE_VERSION }} --app-version ${{ steps.versioning.outputs.IMAGE_VERSION }}

      - name: Helm Repo Update
        run: helm repo update

      - name: Push Helm Chart
        shell: powershell
        run: |
          # Langsung memanggil versi dari ID versioning agar nama file sinkron sempurna
          helm cm-push employee-management-${{ steps.versioning.outputs.IMAGE_VERSION }}.tgz employee-management