replicaCount: 1

image:
  repository: ""
  pullPolicy: Always

spring:
  profiles: docker

secret:
  name: employee-management-secret

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

route:
  host: ""

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

rollout:
  enabled: false
