apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "employee-management-chart.fullname" . }}
  labels:
    app: {{ include "employee-management-chart.name" . }}
    {{- include "employee-management-chart.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "employee-management-chart.fullname" . }}
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None