name: Java CI with Maven + JaCoCo

on:
  push:
    branches: [ "main", "master", "feature-employee-update" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: self-hosted

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Push ke Gitea
      - name: Push current branch to Gitea
        shell: powershell
        run: |
          # Hapus remote jika sudah ada
          git remote remove gitea 2>$null

          # Tambahkan remote Gitea
          git remote add gitea http://${{ secrets.GITEA_USERNAME }}:${{ secrets.GITEA_TOKEN }}@100.103.175.35:3000/reza/employee-management2.git

          # Push branch yang sedang aktif
          git push --force gitea HEAD:${{ github.ref_name }}